name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:

      - name: create string
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          echo "MY_STRING<<EOF" >> $GITHUB_ENV
          echo "$MY_STRING" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash
        id: my_string

      - name: display string
        run: |
          echo "The string is: ${{ env.MY_STRING }}"
