name: Test

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    name: (${{ matrix.config.pkg }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {pkg: "pkgA"}
          - {pkg: "pkgB"}
          
    steps:
      - uses: actions/checkout@v2
      
      # more stuff that actually runs unit tests
      - name: fake unit tests
        run: |
          if [ ${{ matrix.config.pkg }} = 'pkgA' ]; then
            exit 1
          fi
        shell: bash

      - name: set error if tests fail
        id: update-output
        if: ${{ failure() }}
        run: echo "::set-output name=${{ matrix.config.pkg }}::{error}"
        shell: bash

  aggregate-results:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Aggregate results
        run: |
          # how do I loop over all outputs, instead of hardcoding these?
          echo "pkgA: ${{ needs.unit-tests.outputs.pkgA }}"
          echo "pkgB: ${{ needs.unit-tests.outputs.pkgB }}"
        shell: bash

